(define (problem vaccine-prob)
    (:domain vaccine-domain-v22)
    (:objects
        vn no bn td bn-tp qv yp ts tt plane truck-1 truck-2 drone-1 drone-2 drone-3 vaccine-box-1 vaccine-box-2 vaccine-box-3 vaccine-box-4 vaccine-box-5 vaccine-box-6
    )

    (:init
        (state vn)(location vn)
        (region no)(location no)
        (province bn)(location bn)
        (district td)(location td)
        (district bn-tp)(location bn-tp)
        (district qv)(location qv)
        (district yp)(location yp)
        (district ts)(location ts)
        (district tt)(location tt)
        (inside no vn)
        (inside bn no)
        (inside td bn)
        (inside bn-tp bn)
        (inside qv bn)
        (inside yp bn)
        (inside ts bn)
        (inside tt bn)
        (connected vn no)
        (connected no vn)
        (connected no bn)
        (connected bn no)
        (has-airport vn)
        (has-airport no)
        (air-connected vn no)
        (air-connected no vn)
        (plane plane)(vehicle plane)
        (truck truck-1)(vehicle truck-1)
        (truck truck-2)(vehicle truck-2)
        (drone drone-1)(vehicle drone-1)
        (drone drone-2)(vehicle drone-2)
        (drone drone-3)
        (vehicle drone-3)
        (vaccine-box vaccine-box-1)
        (vaccine-box vaccine-box-2)
        (vaccine-box vaccine-box-3)
        (vaccine-box vaccine-box-4)
        (vaccine-box vaccine-box-5)
        (vaccine-box vaccine-box-6)
        (at vaccine-box-1 vn)
        (at vaccine-box-2 vn)
        (at vaccine-box-3 vn)
        (at vaccine-box-4 vn)
        (at vaccine-box-5 vn)
        (at vaccine-box-6 vn)
        (at plane vn)
        (at truck-1 vn)
        (at truck-2 vn)
        (at drone-1 bn)
        (at drone-2 bn)
        (at drone-3 bn)
        (capacity plane l0)
        (capacity truck-1 l0)
        (capacity truck-2 l0)
        (capacity drone-1 l0)
        (capacity drone-2 l0)
        (capacity drone-3 l0)
    )

    (:goal
        (and
            (at vaccine-box-1 td)
            (at vaccine-box-2 bn-tp)
            (at vaccine-box-3 qv)
            (at vaccine-box-4 yp)
            (at vaccine-box-5 ts)
            (at vaccine-box-6 tt)
        )
    )
)